### ISSUE TITLE
Wallet Generates Coins By Default - Linux - 'gen=0' Not Working

### ISSUE THREAD

**Issue by daygle** [cygnusxi/CurecoinSource#49]
I have compiled the Curecoin wallet on a Debian server and have been running for some time.

I have noticed that the wallet generates coins (it appears by default). I don't want the wallet to generate coins so I attempted to stop the generation of coins by adding 'gen=0' to the conf file but this made no difference - coins where still generated.

Are you able to advise how one is to disable the generation of coins in Linux? Why is 'gen=0' not working?

**Comment by Nuitari** [comment]
Why do you not want free coins?

**Comment by daygle** [comment]
I run a cryptocurrency exchange and the code is unable to handle when the wallet generates a coin.

**Comment by cygnusxi** [comment]
You need to use the flag staking=0 because what you are getting is stake blocks (as long as you are on curecoin 2.0+ ). gen=0 was for SHA256 mining that has been removed from the coin.

Ill close this issue but feel free to reopen or contact me if you need help. Join our discord if you need any help troubleshooting. https://discord.gg/jtztkFZ

https://github.com/cygnusxi/CurecoinSource/blob/e213a35cfca2e185a378c3106cf99f13d62bb747/src/init.cpp#L246
